In [5]:
import pandas as pd
df=pd.read_csv("hr_data.csv")
df

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

total no of emp based on department and salarywise

In [12]:
df.pivot_table(index=['department','salary'],values='employee_id',aggfunc='count')

                    employee_id
department  salary
IT          high             83
            low             609
            medium          535
RandD       high             51
            low             364
            medium          372
accounting  high             74
            low             358
            medium          335
hr          high             45
            low             335
            medium          359
management  high            225
            low             180
            medium          225
marketing   high             80
            low             402
            medium          376
product_mng high             68
            low             451
            medium          383
sales       high            269
            low            2099
            medium         1772
support     high            141
            low            1146
            medium          942
technical   high            201
            low            1372
            medium         1147


total no of projects handled by department and salarywise

In [20]:
df.pivot_table(index=['department','salary'],values='number_project',aggfunc='count')

                    number_project
department  salary
IT          high                83
            low                609
            medium             535
RandD       high                51
            low                364
            medium             372
accounting  high                74
            low                358
            medium             335
hr          high                45
            low                335
            medium             359
management  high               225
            low                180
            medium             225
marketing   high                80
            low                402
            medium             376
product_mng high                68
            low                451
            medium             383
sales       high               269
            low               2099
            medium            1772
support     high               141
            low               1146
            medium             942
technical   high               201
            low               1372
            medium            1147