In [73]:
import pandas as pd
df = pd.read_csv("amazon_fires.csv",encoding="latin1")
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  01-01-98
1     1999   Janeiro       Acre  0 Fires  01-01-99
2     2000   Janeiro       Acre  0 Fires  01-01-00
3     2001   Janeiro       Acre  0 Fires  01-01-01
4     2002   Janeiro       Acre  0 Fires  01-01-02
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  01-01-12
6450  2013  Dezembro  Tocantins       85  01-01-13
6451  2014  Dezembro  Tocantins      223  01-01-14
6452  2015  Dezembro  Tocantins      373  01-01-15
6453  2016  Dezembro  Tocantins      119  01-01-16

[6454 rows x 5 columns]

In [75]:
df['mes'].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [77]:
df['numero'].unique()

array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
      dtype=object)

In [79]:
df.dropna(inplace=True)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6322 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6322 non-null   int64
 1   mes       6322 non-null   object
 2   estado    6322 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6322 non-null   object
dtypes: int64(1), object(4)
memory usage: 296.3+ KB

In [83]:
df

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  01-01-98
1     1999   Janeiro       Acre  0 Fires  01-01-99
2     2000   Janeiro       Acre  0 Fires  01-01-00
3     2001   Janeiro       Acre  0 Fires  01-01-01
4     2002   Janeiro       Acre  0 Fires  01-01-02
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  01-01-12
6450  2013  Dezembro  Tocantins       85  01-01-13
6451  2014  Dezembro  Tocantins      223  01-01-14
6452  2015  Dezembro  Tocantins      373  01-01-15
6453  2016  Dezembro  Tocantins      119  01-01-16

[6322 rows x 5 columns]

In [85]:
df.rename(columns={'numero': 'Fires','ano': 'year','mes': 'month','estado': 'city','encontro': 'date'}, inplace=True)
df

      year     month       city    Fires      date
0     1998   Janeiro       Acre  0 Fires  01-01-98
1     1999   Janeiro       Acre  0 Fires  01-01-99
2     2000   Janeiro       Acre  0 Fires  01-01-00
3     2001   Janeiro       Acre  0 Fires  01-01-01
4     2002   Janeiro       Acre  0 Fires  01-01-02
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  01-01-12
6450  2013  Dezembro  Tocantins       85  01-01-13
6451  2014  Dezembro  Tocantins      223  01-01-14
6452  2015  Dezembro  Tocantins      373  01-01-15
6453  2016  Dezembro  Tocantins      119  01-01-16

[6322 rows x 5 columns]

In [89]:
# Step 1: Split and keep only the number part
df['Fires'] = df['Fires'].str.split().str[0]

# Step 2: Convert to numeric (floats if needed)
df['Fires'] = pd.to_numeric(df['Fires'], errors='coerce')

# Step 3: Handle decimals before casting
# Option A: Round to nearest integer
df['Fires'] = df['Fires'].round().astype('Int64')

# Option B: Floor (drop decimal part)
# df['Fires'] = df['Fires'].astype(int)

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6322 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    6322 non-null   int64
 1   month   6322 non-null   object
 2   city    6322 non-null   object
 3   Fires   6322 non-null   Int64
 4   date    6322 non-null   object
dtypes: Int64(1), int64(1), object(3)
memory usage: 302.5+ KB

In [93]:
df

      year     month       city  Fires      date
0     1998   Janeiro       Acre      0  01-01-98
1     1999   Janeiro       Acre      0  01-01-99
2     2000   Janeiro       Acre      0  01-01-00
3     2001   Janeiro       Acre      0  01-01-01
4     2002   Janeiro       Acre      0  01-01-02
...    ...       ...        ...    ...       ...
6449  2012  Dezembro  Tocantins    128  01-01-12
6450  2013  Dezembro  Tocantins     85  01-01-13
6451  2014  Dezembro  Tocantins    223  01-01-14
6452  2015  Dezembro  Tocantins    373  01-01-15
6453  2016  Dezembro  Tocantins    119  01-01-16

[6322 rows x 5 columns]

In [95]:
df.isnull().sum()

year     0
month    0
city     0
Fires    0
date     0
dtype: int64

In [97]:
df['month'].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [103]:
# Define the mapping dictionary
month_map = {
    'Janeiro': 'January',
    'Fevereiro': 'February',
    'Março': 'March',
    'Abril': 'April',
    'Maio': 'May',
    'Junho': 'June',
    'Julho': 'July',
    'Agosto': 'August',
    'Setembro': 'September',
    'Outubro': 'October',
    'Novembro': 'November',
    'Dezembro': 'December'
}

# Option 1: Explicit reassignment (recommended)
df['month'] = df['month'].replace(month_map)

# Option 2: Whole DataFrame replace with dict (safe inplace)
df.replace({'month': month_map}, inplace=True)

In [105]:
df

      year     month       city  Fires      date
0     1998   January       Acre      0  01-01-98
1     1999   January       Acre      0  01-01-99
2     2000   January       Acre      0  01-01-00
3     2001   January       Acre      0  01-01-01
4     2002   January       Acre      0  01-01-02
...    ...       ...        ...    ...       ...
6449  2012  December  Tocantins    128  01-01-12
6450  2013  December  Tocantins     85  01-01-13
6451  2014  December  Tocantins    223  01-01-14
6452  2015  December  Tocantins    373  01-01-15
6453  2016  December  Tocantins    119  01-01-16

[6322 rows x 5 columns]

In [115]:
df['date']=pd.to_datetime(df['date'])
df

      year     month       city  Fires       date
0     1998   January       Acre      0 1998-01-01
1     1999   January       Acre      0 1999-01-01
2     2000   January       Acre      0 2000-01-01
3     2001   January       Acre      0 2001-01-01
4     2002   January       Acre      0 2002-01-01
...    ...       ...        ...    ...        ...
6449  2012  December  Tocantins    128 2012-01-01
6450  2013  December  Tocantins     85 2013-01-01
6451  2014  December  Tocantins    223 2014-01-01
6452  2015  December  Tocantins    373 2015-01-01
6453  2016  December  Tocantins    119 2016-01-01

[6322 rows x 5 columns]

In [121]:
df['date'].dt.month

0       1
1       1
2       1
3       1
4       1
       ..
6449    1
6450    1
6451    1
6452    1
6453    1
Name: date, Length: 6322, dtype: int32

In [123]:
df['date'].dt.day

0       1
1       1
2       1
3       1
4       1
       ..
6449    1
6450    1
6451    1
6452    1
6453    1
Name: date, Length: 6322, dtype: int32

In [125]:
df['date'].dt.year

0       1998
1       1999
2       2000
3       2001
4       2002
        ...
6449    2012
6450    2013
6451    2014
6452    2015
6453    2016
Name: date, Length: 6322, dtype: int32

In [133]:
df[df['date'].dt.year > 2005]

      year     month       city  Fires       date
8     2006   January       Acre      4 2006-01-01
9     2007   January       Acre      0 2007-01-01
10    2008   January       Acre      0 2008-01-01
11    2009   January       Acre      0 2009-01-01
12    2010   January       Acre      1 2010-01-01
...    ...       ...        ...    ...        ...
6449  2012  December  Tocantins    128 2012-01-01
6450  2013  December  Tocantins     85 2013-01-01
6451  2014  December  Tocantins    223 2014-01-01
6452  2015  December  Tocantins    373 2015-01-01
6453  2016  December  Tocantins    119 2016-01-01

[3781 rows x 5 columns]

In [147]:
df[(df['date'].dt.year >= 2005) & (df['date'].dt.year <= 2010) & (df['date'].dt.month.isin([1,2]))]

      year     month       city  Fires       date
7     2005   January       Acre     12 2005-01-01
8     2006   January       Acre      4 2006-01-01
9     2007   January       Acre      0 2007-01-01
10    2008   January       Acre      0 2008-01-01
11    2009   January       Acre      0 2009-01-01
...    ...       ...        ...    ...        ...
6443  2006  December  Tocantins     15 2006-01-01
6444  2007  December  Tocantins     13 2007-01-01
6445  2008  December  Tocantins      7 2008-01-01
6446  2009  December  Tocantins     46 2009-01-01
6447  2010  December  Tocantins     72 2010-01-01

[1899 rows x 5 columns]

# Groupby

* Groupby is used to group the data of the perticular column

* Syntax -----> df.groupby(columnName)

In [171]:
a=df.groupby('month')
a.get_group('January')

      year    month       city  Fires       date
0     1998  January       Acre      0 1998-01-01
1     1999  January       Acre      0 1999-01-01
2     2000  January       Acre      0 2000-01-01
3     2001  January       Acre      0 2001-01-01
4     2002  January       Acre      0 2002-01-01
...    ...      ...        ...    ...        ...
6230  2013  January  Tocantins     50 2013-01-01
6231  2014  January  Tocantins     89 2014-01-01
6232  2015  January  Tocantins    186 2015-01-01
6233  2016  January  Tocantins     42 2016-01-01
6234  2017  January  Tocantins     61 2017-01-01

[532 rows x 5 columns]

In [177]:
a=df.groupby('month').count()
a

           year  city  Fires  date
month
April       528   528    528   528
August      524   524    524   524
December    506   506    506   506
February    535   535    535   535
January     532   532    532   532
July        526   526    526   526
June        533   533    533   533
March       528   528    528   528
May         529   529    529   529
November    526   526    526   526
October     527   527    527   527
September   528   528    528   528

In [183]:
data=df.groupby('month')
jan=data.get_group('January')
jan['Fires'].sum()

47044

In [189]:
data=df.groupby('city')
jan=data.get_group('Rio')
jan['Fires'].sum()

44799

In [191]:
df['city'].value_counts()

city
Rio                 708
Mato Grosso         472
Paraiba             469
alagoas             239
Sao Paulo           236
Ceara               236
Santa Catarina      235
Goias               235
Maranhao            235
Acre                234
Amazonas            234
Distrito Federal    234
pará                234
Roraima             234
Sergipe             233
rondonia            233
Tocantins           233
Piau                233
Bahia               233
Espirito Santo      231
Amapa               231
Minas Gerais        231
Pernambuco          229
Name: count, dtype: int64