In [40]:
import pandas as pd
df = pd.read_csv("C:/Users/DIVY/OneDrive/Desktop/Qspider/Python library/flats_uncleaned.csv")
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...,...
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,NaN,Call for Price

In [41]:
df.isnull().sum().sum()

2818

In [42]:
# df.dropna()

In [43]:
df['description'].unique()

array(['Luxury project with basement parking, Solar rooftop, Gym, Build with advanced machinery and standard materials that last long. Best project for under construction scheme for a happy family life.Read more',
       '2 And 3 BHK Luxurious Flat for Sell In New Althan Area With All Aminities .Read more',
       'This affordable 2 BHK flat is situated along a 200foot road, ensuring easy access and connectivity. Enjoy the convenience of a prime location at a budgetfriendly price. Additionally, it is ready to move in, offering immediate occupancy for your convenience. With a towering 19floor height, it provides impressive views and a sense of elevation.Read more',
       ...,
       'When it comes to beautiful homes, nothing beats us. With our appealing 45 BHK flats, enjoy the beauty of living life the luxurious way. Along with being located in the heart of the city, we are ecoconscious and believe in promoting an ecofriendly lifestyle.Read more',
       'DRB Ravani Cellestial Dreams in Vesu, Surat is a ready to move housing society. It offers apartments in varied budget range. These units are a perfect combination of comfort and style, specifically designed to suit your requirements and conveniences. There are 5BHK apartments available in this project.Read more',
       'Roongta Green Valley is one of the popular residential project in Vesu, Surat. It has lavish yet thoughtfully designed 8 Towers and 208 residences.::::Status::::Under Construction::::Possession by::::Apr 24::::Total Units::::208::::Total Towers::::8::::Project Area::::3 Acre::::Full Address::::Ashirwad Society, Bharthana, Surat, Gujarat::::Pincode::::395003Read more'],
      dtype=object)

In [44]:
df.drop(columns='description',inplace=True,axis =1)
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,NaN,Call for Price

In [45]:
df.dropna(inplace=True)

In [66]:
df.drop(columns='facing',inplace=True,axis =1)
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,"₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,"₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...
4513,"4 BHK Apartment for Sale in Sangini Siddhanta,...",Super Area,4000 sqft,New Property,Ready to Move,5 out of 12,Unfurnished,"₹8,000 per sqft",₹3.20 Cr
4514,4 BHK Apartment for Sale in Millionaires Lifes...,Super Area,3500 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,"₹6,500 per sqft",₹2.27 Cr
4515,"4 BHK Apartment for Sale in Happy Astoria, Ves...",Super Area,3000 sqft,New Property,Poss. by Nov '28,5 out of 12,Unfurnished,"₹6,200 per sqft",₹1.86 Cr
4516,"3 BHK Apartment for Sale in Samprati Palace, V...",Super Area,2620 sqft,Resale,Ready to Move,5 out of 12,Unfurnished,"₹6,031 per sqft",₹1.58 Cr
4517,"4 BHK Apartment for Sale in Samprati Palace, V...",Super Area,3400 sqft,Resale,Ready to Move,5 out of 12,Unfurnished,"₹6,000 per sqft",₹2.04 Cr

In [68]:
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,"₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,"₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...
4513,"4 BHK Apartment for Sale in Sangini Siddhanta,...",Super Area,4000 sqft,New Property,Ready to Move,5 out of 12,Unfurnished,"₹8,000 per sqft",₹3.20 Cr
4514,4 BHK Apartment for Sale in Millionaires Lifes...,Super Area,3500 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,"₹6,500 per sqft",₹2.27 Cr
4515,"4 BHK Apartment for Sale in Happy Astoria, Ves...",Super Area,3000 sqft,New Property,Poss. by Nov '28,5 out of 12,Unfurnished,"₹6,200 per sqft",₹1.86 Cr
4516,"3 BHK Apartment for Sale in Samprati Palace, V...",Super Area,2620 sqft,Resale,Ready to Move,5 out of 12,Unfurnished,"₹6,031 per sqft",₹1.58 Cr
4517,"4 BHK Apartment for Sale in Samprati Palace, V...",Super Area,3400 sqft,Resale,Ready to Move,5 out of 12,Unfurnished,"₹6,000 per sqft",₹2.04 Cr

* in the case of null values obj and numerical columns are treated in different manner

# Obj columns ----->

* In the case of obj columns if there are less nmber of null value that is below 5% it can replace with frequently occurring value

* If more then 70% of data is null then the column is recommended to be drop

* If the null value are between 20-50% & the column is a categorial column, we can replace those  value is unknown

In [95]:
df['furnishing'].value_counts()
# 3607-(2175+422+417)

furnishing
Unfurnished             2175
Semi-Furnished           422
Furnished                417
East                     217
2                         75
                        ...
Raghuvir Spalex            1
Nilkanth Seven Homes       1
50 Open                    1
10 m                       1
7 m                        1
Name: count, Length: 62, dtype: int64

In [97]:
df['furnishing'].unique()

array(['Unfurnished', 'Semi-Furnished', '2', 'Anand Aspire', 'Furnished',
       '1', 'East', '1 Covered,', '1 Covered', 'Freehold', 'West',
       'Main Road', 'North', '1 Open', 'Co-operative Society',
       'Nilkanth Seven Homes', '3', 'Aagam Navkar',
       'Pool, Garden/Park, Main Road', 'Garden/Park, Main Road', '7 m',
       '30 m', '50 Covered,', '12 m', 'Gruham Luxuria', '4', '2 Covered,',
       'Congo', 'North - East', 'Vaishnodevi Ideal Homes',
       'Santvan Lexon', 'Sangini Epitome', 'South -West', '2 Covered',
       '5', 'Raghuvir Spalex', 'South', '50 Open', 'South - East',
       'North - West', '20 m', 'Garden/Park', '10 m', 'Sattvam',
       'Pramukh Amaya', 'Sun Sarvam', '3 Covered', '2 Open', '6 m',
       'Avadh Kimberly', 'Happy Glorious', 'Freedom Tower', '15 m',
       'Surya Signature', '6', 'Green Valley Row House', 'Green Valley',
       'Vatsalya Bungalows', '10 Covered,', 'Ambience',
       'Milestone Pristine', 'Bblossom The Presidency'], dtype=object)

In [ ]:
# Example Series
furnishing = pd.Series([
    'Unfurnished', 'Semi-Furnished', '2', 'Anand Aspire', 'Furnished',
       '1', 'East', '1 Covered,', '1 Covered', 'Freehold', 'West',
       'Main Road', 'North', '1 Open', 'Co-operative Society',
       'Nilkanth Seven Homes', '3', 'Aagam Navkar',
       'Pool, Garden/Park, Main Road', 'Garden/Park, Main Road', '7 m',
       '30 m', '50 Covered,', '12 m', 'Gruham Luxuria', '4', '2 Covered,',
       'Congo', 'North - East', 'Vaishnodevi Ideal Homes',
       'Santvan Lexon', 'Sangini Epitome', 'South -West', '2 Covered',
       '5', 'Raghuvir Spalex', 'South', '50 Open', 'South - East',
       'North - West', '20 m', 'Garden/Park', '10 m', 'Sattvam',
       'Pramukh Amaya', 'Sun Sarvam', '3 Covered', '2 Open', '6 m',
       'Avadh Kimberly', 'Happy Glorious', 'Freedom Tower', '15 m',
       'Surya Signature', '6', 'Green Valley Row House', 'Green Valley',
       'Vatsalya Bungalows', '10 Covered,', 'Ambience',
       'Milestone Pristine', 'Bblossom The Presidency'
])

# Define mapping dictionary
mapping = {
    "Unfurnished": "Unfurnished",
    "Semi-Furnished": "Semi-Furnished",
    "Furnished": "Furnished"
}

# Map values, replace others with "Unknown"
furnishing_cleaned = furnishing.map(mapping).fillna("Unknown")

print(furnishing_cleaned)

In [107]:
# Define valid categories
valid_categories = ["Unfurnished", "Semi-Furnished", "Furnished"]

# Apply function to clean the column
df["furnishing"] = df["furnishing"].apply(
    lambda x: x if x in valid_categories else "Unknown"
)

# Check the cleaned value counts
print(df["furnishing"].value_counts())

furnishing
Unfurnished       2175
Unknown            593
Semi-Furnished     422
Furnished          417
Name: count, dtype: int64

In [109]:
df['furnishing'].unique()

array(['Unfurnished', 'Semi-Furnished', 'Unknown', 'Furnished'],
      dtype=object)

In [115]:
# Define valid categories
valid_categories = ["Unfurnished", "Semi-Furnished", "Furnished"]

# Replace all other values with "Unknown" directly in the original DataFrame
df["furnishing"].replace(
    to_replace=[x for x in df["furnishing"].unique() if x not in valid_categories],
    value="Unknown",
    inplace=True
)

# Verify the changes
print(df["furnishing"].value_counts())

furnishing
Unfurnished       2175
Unknown            593
Semi-Furnished     422
Furnished          417
Name: count, dtype: int64

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3607 entries, 0 to 4517
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   property_name   3607 non-null   object
 1   areaWithType    3607 non-null   object
 2   square_feet     3607 non-null   object
 3   transaction     3607 non-null   object
 4   status          3607 non-null   object
 5   floor           3607 non-null   object
 6   furnishing      3607 non-null   object
 7   price_per_sqft  3607 non-null   object
 8   price           3607 non-null   object
dtypes: object(9)
memory usage: 281.8+ KB

In [127]:
df.isnull().sum()

property_name     0
areaWithType      0
square_feet       0
transaction       0
status            0
floor             0
furnishing        0
price_per_sqft    0
price             0
dtype: int64

In [129]:
df['transaction'].value_counts()

transaction
Resale                  1682
New Property            1426
Unfurnished              309
Semi-Furnished            55
Furnished                 46
2                         19
Congo                     19
3                         17
5                         10
4                          6
1                          4
Orchid Gardenia            3
Soham Elegance             3
Orchid Fantasia            2
Raghuvir Silverstone       2
Casa Rivera                2
6                          1
Co-operative Society       1
Name: count, dtype: int64

In [131]:
df['price'].value_counts()

price
₹50 Lac       76
₹45 Lac       57
₹65 Lac       54
₹55 Lac       51
₹1 Cr         51
              ..
₹73.1 Lac      1
₹94.5 Lac      1
₹81.6 Lac      1
₹69.6 Lac      1
₹6.08 Cr       1
Name: count, Length: 793, dtype: int64

In [135]:
df['transaction'] = [values if values in ["Resale","New Property"] else "unknown" for values in df['transaction']]

In [137]:
df['transaction'].value_counts()

transaction
Resale          1682
New Property    1426
unknown          499
Name: count, dtype: int64

# Numerical columns

* In the case of numerical columns if there are less number of null value that is below 5% it can replace with Median

* And the null value are more than 70% the column is recommended to be dropped

* There are other 2 methods which are use to fill the null values in numerical coulmns butIt should be onlu use one a data in which the values are continuous

1. Forward fill denoted by f-fill
2. Backward fill denoted by b-fill

* and also it is use in date columns

In [152]:
# create a dataframe 4 rows - abcdef marks - 40,55,80,90
import numpy as np
data = {'name' : ['a','b','c','d','aa','bb','d','e','f'],
         'marks' : [40,55,80,90,np.NaN,np.NaN,45,np.NaN,10]}
data = pd.DataFrame(data)
data

  name  marks
0    a   40.0
1    b   55.0
2    c   80.0
3    d   90.0
4   aa    NaN
5   bb    NaN
6    d   45.0
7    e    NaN
8    f   10.0

In [156]:
data['marks'].median()
data.fillna(data['marks'].mean().round())

  name  marks
0    a   40.0
1    b   55.0
2    c   80.0
3    d   90.0
4   aa   53.0
5   bb   53.0
6    d   45.0
7    e   53.0
8    f   10.0