In [341]:
import pandas as pd 

df=pd.read_csv("C:/Users/DIVY/OneDrive/Desktop/Qspider/Python library/titanic.csv")
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

### Boolean filtering

filtering the data based on the condition is called as Boolean filtering

### 1.Get the data of passengers whose pclass is 1

In [320]:
df["pclass"] == 1

0        True
1        True
2        True
3        True
4        True
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Name: pclass, Length: 1309, dtype: bool

### 2.Get the data of only survived passengers.

In [323]:
df[df['survived'] == 1]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0000,0,0,4134,9.5875,NaN,S,1
1277,3,"Vartanian, Mr. David",male,22.0000,0,0,2658,7.2250,NaN,C,1
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0000,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0000,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0000,1,0,2659,14.4542,NaN,C,1

In [325]:
### In the case of embarked column
df['embarked'].unique()

###C --> Cherbourg
###Q --> Queenstown
###S --> SouthAmpton

array(['S', 'C', nan, 'Q'], dtype=object)

### 3. Passengers who embarked from Q and S

In [328]:
df =(df['embarked'] == 'Q') | (df['embarked'] == 'S')
df

0        True
1        True
2        True
3        True
4        True
        ...
1304    False
1305    False
1306    False
1307    False
1308     True
Name: embarked, Length: 1309, dtype: bool

### 4. passengers data who are male and survived

In [337]:
df = (df['sex'] == 'male') & (df['survived'] == 1)
df

0       False
1        True
2       False
3       False
4       False
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Length: 1309, dtype: bool

In [343]:
df['survived'] == 0

0       False
1       False
2        True
3        True
4        True
        ...
1304     True
1305     True
1306     True
1307     True
1308     True
Name: survived, Length: 1309, dtype: bool

### Data Cleaning Steps

1. **Rename the columns**
2. Remove duplicate rows from dataset
3. Changing the data present in dataframe
4. Remove data from unwanted columns
5. Appling in-build functions on columns
6. Handling the missing values
7. Changing the datatype of a particular column
8. **Rearranging the order of columns**
9. Changing the perticular value from the column
10. **Dropping unwanted columns from the dataframe**
11. **Dropping unwanted rows from the dataframe**
12. Rearranging the index
13. **Setting a perticular columns as index**

### 1.Renaming the columns

In the case of Rename of columns, we will create a dictionary which will be consisting of old columnName as the key and the new columnName as the value.

* Syntax ----> 
  df.rename(columns=dictionary,inplace=True)

In [349]:
old=list(df.columns)
new=['Pclass', 'Name', 'Gender', 'Age', 'Sibsp', 'Parch', 'Ticket', 'Fare',
       'Cabin', 'Embarked', 'Survived']

new_columns={}
for i,j in zip(old,new):
    new_columns[i]=j

In [351]:
df.rename(columns=new_columns,inplace=True)

In [353]:
data = pd.DataFrame({
    'ename': ['A', 'B', 'C', 'A' , 'C'],
    'marks': [45,55,78,45,33]
})

print(data)

  ename  marks
0     A     45
1     B     55
2     C     78
3     A     45
4     C     33

# 2. Remove duplicate rows from dataset

* Syntax --->
  df.drop_duplicates()

        inplace=True , ignore_index= True

In [358]:
df.drop_duplicates(inplace=True,ignore_index=True)
df

,Pclass,Name,Gender,Age,Sibsp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

# 3. Changing the data present in dataframe

In [360]:
new_dic = {
    'C' :  'Cherbourg',
    'Q' : 'Queenstown',
    'S' : 'SouthAmpton'
}

new_dic

{'C': 'Cherbourg', 'Q': 'Queenstown', 'S': 'SouthAmpton'}

In [362]:
# dictionary={'old_values1':'new_value2'}
# df['column_name'].map(dictionary)

df['Embarked'].map(new_dic)
df['Embarked']=df['Embarked'].map(new_dic)
df

,Pclass,Name,Gender,Age,Sibsp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,SouthAmpton,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,SouthAmpton,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,SouthAmpton,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,SouthAmpton,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,SouthAmpton,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,Cherbourg,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,Cherbourg,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,Cherbourg,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,Cherbourg,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,SouthAmpton,0