In [9]:
import pandas as pd
df = pd.read_csv("titanic.csv")
d = pd.read_csv("AQI.csv")
d

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",21-02-2026 10:00:00,16.554731,80.649110,PM2.5,NaN,NaN,NaN
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",21-02-2026 10:00:00,16.554731,80.649110,NH3,NaN,NaN,NaN
2,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",21-02-2026 10:00:00,16.554731,80.649110,CO,23.0,51.0,41.0
3,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",21-02-2026 10:00:00,17.720000,83.300000,OZONE,NaN,NaN,NaN
4,India,Arunachal_Pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",21-02-2026 10:00:00,27.103358,93.679645,PM10,100.0,500.0,208.0
...,...,...,...,...,...,...,...,...,...,...,...
3298,India,West_Bengal,Kolkata,"Jadavpur, Kolkata - WBPCB",21-02-2026 10:00:00,22.499290,88.369170,NH3,5.0,12.0,8.0
3299,India,West_Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",21-02-2026 10:00:00,22.511060,88.351420,PM10,102.0,150.0,123.0
3300,India,West_Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",21-02-2026 10:00:00,22.511060,88.351420,SO2,10.0,42.0,21.0
3301,India,West_Bengal,Kolkata,"Victoria, Kolkata - WBPCB",21-02-2026 10:00:00,22.544808,88.340369,SO2,8.0,56.0,25.0
3302,India,West_Bengal,Siliguri,"Ward-32 Bapupara, Siliguri - WBPCB",21-02-2026 10:00:00,26.687923,88.415250,NO2,17.0,21.0,19.0

In [7]:
data = df['name'].str.split()

result=[]
for i in data:
    i[0],i[1]=i[1],i[0]
    result.append(' '.join(i))
df['name']=result
df['name']

0                         Miss. Allen, Elisabeth Walton
1                        Master. Allison, Hudson Trevor
2                          Miss. Allison, Helen Loraine
3                  Mr. Allison, Hudson Joshua Creighton
4       Mrs. Allison, Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Miss. Zabour, Hileni
1305                              Miss. Zabour, Thamine
1306                          Mr. Zakarian, Mapriededer
1307                                Mr. Zakarian, Ortin
1308                                 Mr. Zimmerman, Leo
Name: name, Length: 1309, dtype: object

In [21]:
d['station'].value_counts()

station
Rajiv Nagar, Vijayawada - APPCB                          7
ECIL Kapra, Hyderabad - TSPCB                            7
Sector-3B Avas Vikas Colony, Agra - UPPCB                7
Rohta, Agra - UPPCB                                      7
Manoharpur, Agra - UPPCB                                 7
                                                        ..
Chhatrapati Shivaji Intl. Airport (T2), Mumbai - MPCB    4
Collectorate, Gaya - BSPCB                               4
Shasthri Nagar, Ratlam - IPCA Lab                        4
Sector-2, Rourkela - OSPCB                               3
Khunmoh, Srinagar - JKPCC                                3
Name: count, Length: 497, dtype: int64

In [25]:
# Keep only the first part before the comma in 'station'
d['station'] = d['station'].str.split(',').str[0]

print(d['station'].head())

0        Rajiv Nagar
1        Rajiv Nagar
2        Rajiv Nagar
3    GVM Corporation
4         Naharlagun
Name: station, dtype: object

# 5.Removing Unwanted Columns from dataset

* Syntax ----> df.drop("cloumnName",axis=1,inplace=True)

In [30]:
dd=d['station'].str.split(',')
d['station']=dd[0]

ValueError: Length of values (1) does not match length of index (3303)

In [34]:
d.drop("country", axis=1, inplace=True)
d

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,Andhra_Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,PM2.5,NaN,NaN,NaN
1,Andhra_Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,NH3,NaN,NaN,NaN
2,Andhra_Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,CO,23.0,51.0,41.0
3,Andhra_Pradesh,Visakhapatnam,GVM Corporation,21-02-2026 10:00:00,17.720000,83.300000,OZONE,NaN,NaN,NaN
4,Arunachal_Pradesh,Naharlagun,Naharlagun,21-02-2026 10:00:00,27.103358,93.679645,PM10,100.0,500.0,208.0
...,...,...,...,...,...,...,...,...,...,...
3298,West_Bengal,Kolkata,Jadavpur,21-02-2026 10:00:00,22.499290,88.369170,NH3,5.0,12.0,8.0
3299,West_Bengal,Kolkata,Rabindra Sarobar,21-02-2026 10:00:00,22.511060,88.351420,PM10,102.0,150.0,123.0
3300,West_Bengal,Kolkata,Rabindra Sarobar,21-02-2026 10:00:00,22.511060,88.351420,SO2,10.0,42.0,21.0
3301,West_Bengal,Kolkata,Victoria,21-02-2026 10:00:00,22.544808,88.340369,SO2,8.0,56.0,25.0
3302,West_Bengal,Siliguri,Ward-32 Bapupara,21-02-2026 10:00:00,26.687923,88.415250,NO2,17.0,21.0,19.0

In [72]:
d['state'].unique()
d['state']=d['state'].str.replace('_',' ')
d

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,Andhra Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,PM2.5,0,0,0
1,Andhra Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,NH3,0,0,0
2,Andhra Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,CO,0,0,0
3,Andhra Pradesh,Visakhapatnam,GVM Corporation,21-02-2026 10:00:00,17.720000,83.300000,OZONE,0,0,0
4,Arunachal Pradesh,Naharlagun,Naharlagun,21-02-2026 10:00:00,27.103358,93.679645,PM10,0,0,0
...,...,...,...,...,...,...,...,...,...,...
3298,West Bengal,Kolkata,Jadavpur,21-02-2026 10:00:00,22.499290,88.369170,NH3,0,0,0
3299,West Bengal,Kolkata,Rabindra Sarobar,21-02-2026 10:00:00,22.511060,88.351420,PM10,0,0,0
3300,West Bengal,Kolkata,Rabindra Sarobar,21-02-2026 10:00:00,22.511060,88.351420,SO2,0,0,0
3301,West Bengal,Kolkata,Victoria,21-02-2026 10:00:00,22.544808,88.340369,SO2,0,0,0
3302,West Bengal,Siliguri,Ward-32 Bapupara,21-02-2026 10:00:00,26.687923,88.415250,NO2,0,0,0

In [52]:
import numpy as np
d['pollutant_avg'].replace('NaN','0')
d['pollutant_avg']

0         NaN
1         NaN
2        41.0
3         NaN
4       208.0
        ...
3298      8.0
3299    123.0
3300     21.0
3301     25.0
3302     19.0
Name: pollutant_avg, Length: 3303, dtype: float64

In [70]:
d['pollutant_avg'] = d['pollutant_avg'].replace('NaN', 0)
# d['pollutant_avg'] = d['pollutant_avg'].fillna(0)
# d['pollutant_min'] = d['pollutant_min'].fillna(0)
# d['pollutant_max'] = d['pollutant_max'].fillna(0)
d

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,Andhra Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,PM2.5,0,0,0
1,Andhra Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,NH3,0,0,0
2,Andhra Pradesh,Vijayawada,Rajiv Nagar,21-02-2026 10:00:00,16.554731,80.649110,CO,0,0,0
3,Andhra Pradesh,Visakhapatnam,GVM Corporation,21-02-2026 10:00:00,17.720000,83.300000,OZONE,0,0,0
4,Arunachal Pradesh,Naharlagun,Naharlagun,21-02-2026 10:00:00,27.103358,93.679645,PM10,0,0,0
...,...,...,...,...,...,...,...,...,...,...
3298,West Bengal,Kolkata,Jadavpur,21-02-2026 10:00:00,22.499290,88.369170,NH3,0,0,0
3299,West Bengal,Kolkata,Rabindra Sarobar,21-02-2026 10:00:00,22.511060,88.351420,PM10,0,0,0
3300,West Bengal,Kolkata,Rabindra Sarobar,21-02-2026 10:00:00,22.511060,88.351420,SO2,0,0,0
3301,West Bengal,Kolkata,Victoria,21-02-2026 10:00:00,22.544808,88.340369,SO2,0,0,0
3302,West Bengal,Siliguri,Ward-32 Bapupara,21-02-2026 10:00:00,26.687923,88.415250,NO2,0,0,0

In [58]:
import numpy as np

# Replace NaN (actual missing values) with 0
d['pollutant_avg'].fillna(0, inplace=True)

C:\Users\DIVY\AppData\Local\Temp\ipykernel_21272\3893966431.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['pollutant_avg'].fillna(0, inplace=True)